theme: minima
title: Gangatuan Blog
author: b0red-grinch
email: raphesezobor@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Alright then. I'll write a description y'all keep bothering me about unnecessary stuff like this.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
